### ISSUE TITLE
Potential thread safety issue with LzoDecompressor

### ISSUE THREAD

**Issue by EugenCepoi** [twitter/hadoop-lzo#106] opened 2015-05-20 20:50 UTC
The problem occurs when trying to read lzo compressed files with spark using sc.textFile(...).
But works fine when using LzoTextInputFormat, with the same dataset and job config.

I encounter multiple 

```
java.lang.InternalError: lzo1x_decompress_safe returned: -6
	at com.hadoop.compression.lzo.LzoDecompressor.decompressBytesDirect(Native Method)
	at com.hadoop.compression.lzo.LzoDecompressor.decompress(LzoDecompressor.java:315)
	at com.hadoop.compression.lzo.LzopDecompressor.decompress(LzopDecompressor.java:122)
	at com.hadoop.compression.lzo.LzopInputStream.decompress(LzopInputStream.java:252)
	at org.apache.hadoop.io.compress.DecompressorStream.read(DecompressorStream.java:85)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.hadoop.util.LineReader.fillBuffer(LineReader.java:180)
```

And sometime few

```
Compressed length 892154724 exceeds max block size 67108864 (probably corrupt file)
  at com.hadoop.compression.lzo.LzopInputStream.getCompressedData(LzopInputStream.java:291)
```

Those happen only when having multiple threads per jvm (multiple executor-cores).
We are using a snapshot version of 0.4.20 starting from [this commit](https://github.com/twitter/hadoop-lzo/commits/e8c11c2be93b965abb548411379b203dabcbce79).

Thanks

**Comment by rangadi** [comment] 2015-05-20 21:11
I think this was fixed in #103

**Comment by EugenCepoi** [comment] 2015-05-21 11:12
Just tried with latest commit but the problem remains

**Comment by rangadi** [comment] 2015-05-22 18:52
too bad. Does each thread read from a different file or do multiple threads read from the same file? anything you can add here to reproduce easily will be very useful.

**Comment by EugenCepoi** [comment] 2015-05-25 10:41
So it looks like it is due to something that changed in hadoop 2 and when using the basic textFile method from spark it expects the input to be splittable (in my case the files are not indexed).

Discussed on [SO](http://stackoverflow.com/questions/25248170/spark-hadoop-throws-exception-for-large-lzo-files). Anyway using the input format avoids this problem. 

Should I close this issue?

**Closed** 2015-05-29 09:30 UTC

**Comment by rangadi** [comment] 2015-05-29 21:32
So this was in fact because of reader trying to read from an arbitrary offset, right? Thanks for the update.

**Comment by LTzycLT** [comment] 2016-05-23 08:26
So will it be fixed in the future version? I hope sc.textFile can decompress and split any input files correctly and automatically.

**Comment by EugenCepoi** [comment] 2016-05-23 16:52
I don't know if it has been fixed but you can use LzoTextInputFormat with the lower level api methods where you can specify the input format to avoid this problem.

**Comment by leafjungle** [comment] 2019-03-06 03:55
I meet the same problem. is it fixed on higher version? I am now using hadoop-lzo-0.4.19.jar ( it looks like be published on 2011 or 2013, too old).
