### ISSUE TITLE
Unable to set the queuename 

### ISSUE THREAD

**Issue by amitmittal5** [twitter/hadoop-lzo#112] opened 2016-04-25 11:31 UTC
Hello,

I am indexing the lzo files using map-reduce as per below command (on CDH 5.5.1).
hadoop jar /path/to/your/hadoop-lzo.jar com.hadoop.compression.lzo.DistributedLzoIndexer  -Dmapreduce.job.queuename=root.test  big_file.lzo

The problem is the job is not using the queuename specified on the command line, it's taking default queue. On other hand, if I just execute the PI example, it uses the specified queue:
hadoop jar /opt/cloudera/parcels/CDH/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar pi  -Dmapreduce.job.queuename=root.test 10 100

Can you please advise how I can use the non-default queue, Thanks.

**Comment by sjlee** [comment] 2016-04-25 17:43
I don't know why mapreduce.job.queuename would not be set. It is a hadoop property passed via -D.

@gsteelman, we do use this param, correct? Could you comment?

**Comment by amitmittal5** [comment] 2016-04-27 06:42
Thanks **@sjlee ** Additional information, we are using 0.4.15 version. "hadoop-lzo-0.4.15-cdh5.5.1.jar"
I retried, but same issue.

Hello **@gsteelman**, Did you get a chance to check, Thanks a lot !

**Comment by sjlee** [comment] 2016-09-27 14:25
Sorry it took me a while, but I just tested it against the latest master version, and it seems to work fine. I added a line in the configuration that prints out the queue name. I also checked the job itself is indeed launched under queue "root.test":

> [hadoop-lzo (master)]$ hadoop jar target/hadoop-lzo-0.4.20-SNAPSHOT.jar com.hadoop.compression.lzo.DistributedLzoIndexer -Dmapreduce.job.queuename=root.test my_lzo_file.lzo
16/09/27 10:19:32 INFO lzo.GPLNativeCodeLoader: Loaded native gpl library from the embedded binaries
16/09/27 10:19:32 INFO lzo.LzoCodec: Successfully loaded & initialized native-lzo library [hadoop-lzo rev 41400f3bee8f99017bfc7ce01c33f790e46e48f2]
16/09/27 10:19:32 INFO lzo.DistributedLzoIndexer: queue name: root.test

I'll go ahead and close the issue as I cannot reproduce it against master. Please let me know if you have a reproducible scenario against the latest master.

**Closed by sjlee** 2016-09-27 14:25 UTC
